### ISSUE TITLE
Error occurred when uploading using OkHttp stack

### ISSUE THREAD

**Issue by hendrawd** [gotev/android-upload-service#118]
I declared OkHttpClient to my app class with this
OkHttpClient client = new OkHttpClient();
UploadService.HTTP_STACK = new OkHttpStack(client); // you pass your own client

This is what my gradle compiles:
compile 'net.gotev:uploadservice:2.1@aar'
compile 'net.gotev:uploadservice-okhttp:2.1@aar'
compile 'com.squareup.okhttp3:okhttp:3.2.0'

But when uploading, an error occurred.

Stack trace:
Error in upload with ID: anId. Attempt to invoke interface method 'void net.gotev.uploadservice.http.HttpConnection.close()' on a null object reference
                                                                                                                java.lang.NullPointerException: Attempt to invoke interface method 'void net.gotev.uploadservice.http.HttpConnection.close()' on a null object reference
                                                                                                                    at net.gotev.uploadservice.HttpUploadTask.upload(HttpUploadTask.java:174)
                                                                                                                    at net.gotev.uploadservice.HttpUploadTask.run(HttpUploadTask.java:102)
                                                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                                    at java.lang.Thread.run(Thread.java:818)

**Comment by hendrawd** [comment]
i changed
compile 'net.gotev:uploadservice:2.1@aar'
compile 'net.gotev:uploadservice-okhttp:2.1@aar'
to
compile 'net.gotev:uploadservice:2.1'
compile 'net.gotev:uploadservice-okhttp:2.1'
and the problem gone

**Comment by gotev** [comment]
Thank you for the report. Modified [Setup](https://github.com/gotev/android-upload-service/wiki/Setup) wiki page
