### ISSUE TITLE
java.lang.OutOfMemoryError exception

### ISSUE THREAD

**Issue by neilyoung** [gotev/android-upload-service#159]
Hi,
one of my customers is attempting to upload a 134 MB video and catches an OutOfMemoy exception. Is there anything what can be done to prevent this?

I'm using your lib like this

      compile 'net.gotev:uploadservice:2.0.1@aar'

The exception is:

    07-31 17:42:18.647 E/dalvikvm-heap( 3890): Out of memory on a 134212394-byte allocation.
    07-31 17:42:18.647 I/dalvikvm( 3890): "pool-149-thread-1" prio=5 tid=62 RUNNABLE
    07-31 17:42:18.647 I/dalvikvm( 3890):   | group="main" sCount=0 dsCount=0 obj=0x44957a30 self=0x84b46b00
    07-31 17:42:18.647 I/dalvikvm( 3890):   | sysTid=4969 nice=0 sched=0/0 cgrp=apps handle=-2109757056
    07-31 17:42:18.647 I/dalvikvm( 3890):   | state=R schedstat=( 859607928 104574720 1143 ) utm=61 stm=24 core=0
    07-31 17:42:18.647 I/dalvikvm( 3890):   at java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:~91)
    07-31 17:42:18.647 I/dalvikvm( 3890):   at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:201)
    07-31 17:42:18.657 I/dalvikvm( 3890):   at com.android.okhttp.internal.http.RetryableOutputStream.write(RetryableOutputStream.java:64)
    07-31 17:42:18.657 I/dalvikvm( 3890):   at net.gotev.uploadservice.HttpUploadTask.writeStream(HttpUploadTask.java:326)
    07-31 17:42:18.657 I/dalvikvm( 3890):   at net.gotev.uploadservice.MultipartUploadTask.writeFiles(MultipartUploadTask.java:131)
    07-31 17:42:18.657 I/dalvikvm( 3890):   at net.gotev.uploadservice.MultipartUploadTask.writeBody(MultipartUploadTask.java:64)
    07-31 17:42:18.657 I/dalvikvm( 3890):   at net.gotev.uploadservice.HttpUploadTask.upload(HttpUploadTask.java:167)
    07-31 17:42:18.657 I/dalvikvm( 3890):   at net.gotev.uploadservice.HttpUploadTask.run(HttpUploadTask.java:113)
    07-31 17:42:18.657 I/dalvikvm( 3890):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    07-31 17:42:18.657 I/dalvikvm( 3890):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    07-31 17:42:18.657 I/dalvikvm( 3890):   at java.lang.Thread.run(Thread.java:841)
    
The videofile already exists on SD and I'm just forwarding you the path while attempting to upload.

                        .addFileToUpload(videoFile, "VIDEO")

**Comment by gotev** [comment]
This is a bug in the OkHttp version used internally by your Android version. What I suggest you to do is upgrade to 3.0 and use the OkHttp stack implementation, so you will get a newer OkHttp version without that bug

**Comment by neilyoung** [comment]
Thanks for the suggestions. I suppose I should try to follow this guide? 
https://github.com/gotev/android-upload-service/wiki/Setup#use-custom-http-stack

**Comment by neilyoung** [comment]
Please allow me an additional question: I'm not instantiating an instance of your UploadService. Instead I'm using kind of this:

                  new MultipartUploadRequest(mContext, uploadID, serverUrlString)
                        .setBasicAuth(username, password)
                        .addFileToUpload(videoFile, "VIDEO")
                        .addParameter("PANORAMA", ""+panorama)
                        .setMaxRetries(1)
                        .startUpload();

Will that incorporate the proper OkHttp version then as well?

**Comment by neilyoung** [comment]
My implementation is now no longer compiling properly. Seems the UploadServiceBroadcastReceiver has changed...

**Comment by gotev** [comment]
@neilyoung yes, follow the instructions [here](https://github.com/gotev/android-upload-service/wiki/Setup) to upgrade from an older release.

**Comment by neilyoung** [comment]
BTW: The fix did NOT help.  Here is the old crashdump followed by the new one

   STACK_TRACE=java.lang.OutOfMemoryError
    at java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:91)
    at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:201)
    at com.android.okhttp.internal.http.RetryableOutputStream.write(RetryableOutputStream.java:64)
    at net.gotev.uploadservice.HttpUploadTask.writeStream(HttpUploadTask.java:326)
    at net.gotev.uploadservice.MultipartUploadTask.writeFiles(MultipartUploadTask.java:131)
    at net.gotev.uploadservice.MultipartUploadTask.writeBody(MultipartUploadTask.java:64)
    at net.gotev.uploadservice.HttpUploadTask.upload(HttpUploadTask.java:167)
    at net.gotev.uploadservice.HttpUploadTask.run(HttpUploadTask.java:113)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)
    
    
    STACK_TRACE=java.lang.OutOfMemoryError
    at java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:91)
    at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:201)
    at com.android.okhttp.internal.http.RetryableOutputStream.write(RetryableOutputStream.java:64)
    at net.gotev.uploadservice.http.impl.HurlStackConnection.writeBody(HurlStackConnection.java:84)
    at net.gotev.uploadservice.HttpUploadTask.writeStream(HttpUploadTask.java:109)
    at net.gotev.uploadservice.MultipartUploadTask.writeFiles(MultipartUploadTask.java:147)
    at net.gotev.uploadservice.MultipartUploadTask.writeBody(MultipartUploadTask.java:64)
    at net.gotev.uploadservice.HttpUploadTask.upload(HttpUploadTask.java:68)
    at net.gotev.uploadservice.UploadTask.run(UploadTask.java:139)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)

Looks pretty much similar.

**Comment by gotev** [comment]
@neilyoing are you sure you are using the OkHttp stack? Show me how you initialize the library
