### ISSUE TITLE
Make OkHttp the default stack

### ISSUE THREAD

**Issue by gotev** [gotev/android-upload-service#165]
Due to many errors such as `OutOfMemoryException` and other strange behaviours described by library users, use `OkHttp` stack as the default HTTP stack in the next release. Also, update it to the last stable version available.

**Comment by NitroG42** [comment]
Using the latest version of OkHttp would be great, because if we're using another library that uses the version 3.3.1 will make a 
```
Fatal Exception: java.lang.NoSuchMethodError: No virtual method recover(Ljava/io/IOException;)Lokhttp3/internal/http/HttpEngine; in class Lokhttp3/internal/http/HttpEngine; or its super classes (declaration of 'okhttp3.internal.http.HttpEngine' appears in /data/app/com.bweez.app-2/base.apk:classes2.dex)
       at okhttp3.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:493)
       at okhttp3.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
       at okhttp3.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:261)
       at net.gotev.uploadservice.okhttp.OkHttpStackConnection.writeBody(OkHttpStackConnection.java:74)
       at net.gotev.uploadservice.MultipartUploadTask.writeFiles(MultipartUploadTask.java:139)
       at net.gotev.uploadservice.MultipartUploadTask.writeBody(MultipartUploadTask.java:64)
       at net.gotev.uploadservice.HttpUploadTask.upload(HttpUploadTask.java:68)
       at net.gotev.uploadservice.UploadTask.run(UploadTask.java:139)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```
It happens if we try an upload without any internet connection.
Right now the only way is to fork the library and update the okhttp version which is kind of annoying.

**Comment by gotev** [comment]
The version of OkHttp will be upgraded to the latest in the next release

**Comment by gotev** [comment]
@NitroG42 check the 3.0.1 release which uses OkHttp 3.4.1

**Comment by gotev** [comment]
To make the library core light, OkHttp is NOT the default HTTP stack in 3.1 (check #122)
