### ISSUE TITLE
okhttp exception

### ISSUE THREAD

**Issue by AndrewBryukhov** [gotev/android-upload-service#169]
> 08-04 14:04:34.560 4474-9425/package.com D/UploadService: OkHttpStackConnection - closing connection
08-04 14:04:34.661 4474-9425/package.com E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
                                                            Process: package.com, PID: 4474
                                                            java.lang.NoSuchMethodError: No virtual method internalCache(Lokhttp3/OkHttpClient;)Lokhttp3/internal/InternalCache; in class Lokhttp3/internal/Internal; or its super classes (declaration of 'okhttp3.internal.Internal' appears in /data/data/package.com/files/instant-run/dex/slice-okhttp-3.4.1_ec7308667a1c580313f7796370c10373cd70b1b4-classes.dex)
                                                                at okhttp3.internal.huc.HttpURLConnectionImpl.newHttpEngine(HttpURLConnectionImpl.java:390)
                                                                at okhttp3.internal.huc.HttpURLConnectionImpl.initHttpEngine(HttpURLConnectionImpl.java:341)
                                                                at okhttp3.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:410)
                                                                at okhttp3.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:247)
                                                                at net.gotev.uploadservice.okhttp.OkHttpStackConnection.close(OkHttpStackConnection.java:153)
                                                                at net.gotev.uploadservice.HttpUploadTask.upload(HttpUploadTask.java:86)
                                                                at net.gotev.uploadservice.UploadTask.run(UploadTask.java:139)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                at java.lang.Thread.run(Thread.java:818)

```
        httpClient = new OkHttpClient.Builder();

        httpClient.addInterceptor(new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                Request original = chain.request();
                Request.Builder requestBuilder;

                requestBuilder = original.newBuilder()
                        .header("Authorization", getBasic())
                        .header("X-Csrf-Token", tokenAndCookie[0])
                        .header("Cookie", tokenAndCookie[1])
                        .header("Slug", slug)
                        .method(original.method(), original.body());

                Request request = requestBuilder.build();
                return chain.proceed(request);
            }
        });

        OkHttpClient client = httpClient.build();

        UploadService.HTTP_STACK = new OkHttpStack(client);
```

**Comment by gotev** [comment]
As is specified in the [Setup Wiki](https://github.com/gotev/android-upload-service/wiki/Setup) page:
> Bear in mind that you can't use request interceptors to set request headers and parameters (#122). You have to set them using the proper UploadRequest methods.

**Comment by AndrewBryukhov** [comment]
I can't set headers with UploadRequest
