### ISSUE TITLE
Crash on UploadServiceBroadcastReceiver's BroadcastData

### ISSUE THREAD

**Issue by hendrawd** [gotev/android-upload-service#195]
### Version info
* Android Upload Service version: Not sure, maybe 3.0.3
* Android version and API version: JellyBean, 4.1.1
* HTTP stack (e.g. HurlStack or OkHttpStack): Default stack

### What did you expect?
Not crash

### What happened instead?
Crash

### Steps to reproduce (if applicable):
It is from Crashlytics dashboard, so i don't really know how to reproduce it.

### Library initialization code:
```java
UploadService.NAMESPACE = BuildConfig.APPLICATION_ID;
```
That's all

### Request code:
```java
final MultipartUploadRequest multipartUploadRequest = new MultipartUploadRequest(this, mCurrentPhotoPath, url)
                 .addFileToUpload(uriToUpload.getPath(), "file")
                 .setNotificationConfig(getNotificationConfig(mCurrentPhotoPath))
                 .addParameter("some_parameter", "some_value")
                 .addHeader("some_cookie", "some_cookie_value");
                 .setMaxRetries(0);
multipartUploadRequest.startUpload();
```
#### Where have you added the request code?
- [x] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
It is the stack trace from Crashlytics dashboard
```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver my.application.package.receiver.MyReceiver: java.lang.NullPointerException
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2325)
       at android.app.ActivityThread.access$1500(ActivityThread.java:130)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1287)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4847)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:535)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at net.gotev.uploadservice.UploadServiceBroadcastReceiver.onReceive(UploadServiceBroadcastReceiver.java:30)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2312)
       at android.app.ActivityThread.access$1500(ActivityThread.java:130)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1287)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4847)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:535)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

### Server side
I don't have access to the server code, so i don't know how server handle, but it is a standard PHP upload i think.

### Additional info
![screen shot 2016-09-27 at 5 29 15 pm](https://cloud.githubusercontent.com/assets/9481791/18869700/a52b4640-84d7-11e6-8344-261cf5980b95.png)
I dive to UploadServiceBroadcastReceiver line 30 and see this line
```
switch (data.getStatus()) {
```
So i think it has something to do with BroadcastData or Status that null

**Comment by gotev** [comment]
TMMARS is a cloud software from [TrendMicro](https://mars.trendmicro.com/). Added defensive programming statements to prevent NullPointerExceptions and log the conditions which previously arised them. The fix will be available in 3.1. Thank you for the report!
