### ISSUE TITLE
Demo app: file picker not working on Android 7

### ISSUE THREAD

**Issue by gotev** [gotev/android-upload-service#200]
After selecting a file for upload on Android 7, the following exception gets raised:
```java
android.os.FileUriExposedException: file:///storage/emulated/0/Download/12716320_1029986900381445_2238459154914449891_o.jpg exposed beyond app through ClipData.Item.getUri()
   at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
   at android.net.Uri.checkFileUriExposed(Uri.java:2346)
   at android.content.ClipData.prepareToLeaveProcess(ClipData.java:832)
   at android.content.Intent.prepareToLeaveProcess(Intent.java:8909)
   at android.content.Intent.prepareToLeaveProcess(Intent.java:8894)
   at android.app.Activity.finish(Activity.java:5188)
   at android.app.Activity.finish(Activity.java:5208)
   at com.nononsenseapps.filepicker.AbstractFilePickerActivity.onFilesPicked(AbstractFilePickerActivity.java:165)
   at com.nononsenseapps.filepicker.AbstractFilePickerFragment.onClickOk(AbstractFilePickerFragment.java:285)
   at com.nononsenseapps.filepicker.AbstractFilePickerFragment$2.onClick(AbstractFilePickerFragment.java:192)
   at android.view.View.performClick(View.java:5609)
   at android.view.View$PerformClick.run(View.java:22262)
   at android.os.Handler.handleCallback(Handler.java:751)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:154)
   at android.app.ActivityThread.main(ActivityThread.java:6077)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```
From [FileUriExposedException](https://developer.android.com/reference/android/os/FileUriExposedException.html):

The exception that is thrown when an application exposes a file:// Uri to another app.

This exposure is discouraged since the receiving app may not have access to the shared path. For example, the receiving app may not have requested the READ_EXTERNAL_STORAGE runtime permission, or the platform may be sharing the Uri across user profile boundaries.

Instead, apps should use content:// Uris so the platform can extend temporary permission for the receiving app to access the resource.

This is only thrown for applications targeting N or higher. Applications targeting earlier SDK versions are allowed to share file:// Uri, but it's strongly discouraged.

**Comment by gotev** [comment]
Signaled to https://github.com/spacecowboy/NoNonsense-FilePicker/issues/115
