### ISSUE TITLE
NoClassDefFoundError: net.gotev.uploadservice.http.impl.HurlStack

### ISSUE THREAD

**Issue by willkernel** [gotev/android-upload-service#205]
there is a exception at 'UploadService.NAMESPACE = BuildConfig.APPLICATION_ID' in Application

`AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.app, PID: 11217
                                                                            java.lang.NoClassDefFoundError: net.gotev.uploadservice.http.impl.HurlStack
                                                                                at net.gotev.uploadservice.UploadService.<clinit>(UploadService.java:68)
                                                                                at App.onCreate(CApp.java:42)
                                                                                at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4328)
                                                                                at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                                at dalvik.system.NativeStart.main(Native Method)`

**Comment by gotev** [comment]
This seems to be happening in a test environment. Add some more details.

**Comment by willkernel** [comment]
I have solved the problem by removing the following codes ,beacuse there is a conflict when i use RMP
```java
realm {
    syncEnabled = true;
}
```
