### ISSUE TITLE
"WakeLock under-locked UploadService" in version 3.0.3

### ISSUE THREAD

**Issue by hendrawd** [gotev/android-upload-service#214]
### Version info
* Android Upload Service version: 3.0.3
* Android version and API version: 5.1
* HTTP stack (e.g. HurlStack or OkHttpStack): HurlStack

### What did you expect?
Not crash

### What happened instead?
Crash

### Steps to reproduce (if applicable):
I don't really know how to reproduce it. I just uploading some files maybe the same file in a short of time.

### Library initialization code:
```java
UploadService.NAMESPACE = BuildConfig.APPLICATION_ID;
```

### Request code:
```java
final MultipartUploadRequest multipartUploadRequest = new MultipartUploadRequest(this, mCurrentPhotoPath, url)
.setNotificationConfig(getNotificationConfig(mCurrentPhotoPath))
.setMaxRetries(0);
multipartUploadRequest.addFileToUpload(uriToUpload.getPath(), "file");
multipartUploadRequest.addParameter("some param key", "value");
multipartUploadRequest.addHeader("some cookie key", "value");
multipartUploadRequest.startUpload();
```
#### Where have you added the request code?
- [x] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
Sorry, i didn't set the log level to DEBUG when the crash happened, but here is the crash log
```
Fatal Exception: java.lang.RuntimeException: Unable to stop service net.gotev.uploadservice.UploadService@208e6e2b: java.lang.RuntimeException: WakeLock under-locked UploadService
       at android.app.ActivityThread.handleStopService(ActivityThread.java:3329)
       at android.app.ActivityThread.access$2200(ActivityThread.java:185)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1675)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5847)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1010)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
Caused by java.lang.RuntimeException: WakeLock under-locked UploadService
       at android.os.PowerManager$WakeLock.release(PowerManager.java:1192)
       at android.os.PowerManager$WakeLock.release(PowerManager.java:1163)
       at net.gotev.uploadservice.UploadService.onDestroy(UploadService.java:258)
       at android.app.ActivityThread.handleStopService(ActivityThread.java:3310)
       at android.app.ActivityThread.access$2200(ActivityThread.java:185)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1675)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5847)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1010)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
```

### Additional info
There are already same issues https://github.com/gotev/android-upload-service/issues?utf8=%E2%9C%93&q=wakelock but i read that it has been [resolved in version 3.0.3](https://github.com/gotev/android-upload-service/issues/175). I used version 3.0.3, checked the code of UploadService.java at line 257 and 258
```java
if (wakeLock != null && wakeLock.isHeld())
            wakeLock.release();
```
But the problem still exist.

**Comment by gotev** [comment]
Made a fix and added to 3.1 dev version. You can try it from JitPack.

```groovy
repositories {
    maven { url 'https://jitpack.io' }
}
```

```groovy
compile 'com.github.gotev:android-upload-service:0bf8fdc257'
```
Let me know if the issue can be considered fixed. Thank you!

**Comment by hendrawd** [comment]
I will check it

**Comment by gotev** [comment]
@hendrawd can I consider the issue as solved?

**Comment by hendrawd** [comment]
i can't test it yet, but i will re-open this issue next time if it re-occured
