### ISSUE TITLE
Getting NoSuchMethodException in multipart request

### ISSUE THREAD

**Issue by praveen-xymob** [gotev/android-upload-service#216]
### Version info
* This is the latest code I am trying.

### Steps to reproduce (if applicable):
Select file to upload then press multipart.

### Exception getting is
net.gotev.uploadservicedemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: net.gotev.uploadservicedemo, PID: 4283
                                                                           java.lang.RuntimeException: java.lang.NoSuchMethodException: <init> [class java.lang.String]
                                                                               at net.gotev.uploadservice.UploadFile.<init>(UploadFile.java:50)
                                                                               at net.gotev.uploadservice.MultipartUploadRequest.addFileToUpload(MultipartUploadRequest.java:83)
                                                                               at net.gotev.uploadservice.MultipartUploadRequest.addFileToUpload(MultipartUploadRequest.java:149)
                                                                               at net.gotev.uploadservicedemo.MainActivity.onMultipartUploadClick(MainActivity.java:124)
                                                                               at net.gotev.uploadservicedemo.MainActivity_ViewBinding$1.doClick(MainActivity_ViewBinding.java:42)
                                                                               at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                               at android.view.View.performClick(View.java:5697)
                                                                               at android.widget.TextView.performClick(TextView.java:10815)
                                                                               at android.view.View$PerformClick.run(View.java:22526)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:158)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                            Caused by: java.lang.NoSuchMethodException: <init> [class java.lang.String]
                                                                               at java.lang.Class.getConstructor(Class.java:528)
                                                                               at java.lang.Class.getConstructor(Class.java:492)
                                                                               at net.gotev.uploadservice.schemehandlers.SchemeHandlerFactory.get(SchemeHandlerFactory.java:33)
                                                                               at net.gotev.uploadservice.UploadFile.<init>(UploadFile.java:48)
                                                                               at net.gotev.uploadservice.MultipartUploadRequest.addFileToUpload(MultipartUploadRequest.java:83) 
                                                                               at net.gotev.uploadservice.MultipartUploadRequest.addFileToUpload(MultipartUploadRequest.java:149) 
                                                                               at net.gotev.uploadservicedemo.MainActivity.onMultipartUploadClick(MainActivity.java:124) 
                                                                               at net.gotev.uploadservicedemo.MainActivity_ViewBinding$1.doClick(MainActivity_ViewBinding.java:42) 
                                                                               at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22) 
                                                                               at android.view.View.performClick(View.java:5697) 
                                                                               at android.widget.TextView.performClick(TextView.java:10815) 
                                                                               at android.view.View$PerformClick.run(View.java:22526) 
                                                                               at android.os.Handler.handleCallback(Handler.java:739) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                               at android.os.Looper.loop(Looper.java:158) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
12-15 23:39:55.541 4283-4283/net.gotev.uploadservicedemo I/Process: Sending signal. PID: 4283 SIG: 9

Please help to fix the problem.

**Comment by gotev** [comment]
Are you using the last stable version from gradle dependency (3.0.3) or the latest master revision?

**Comment by praveen-xymob** [comment]
Thanks for reply. I am using latest master version. Shall I use it using gradle 3.0.3 to fix this issue?

**Comment by gotev** [comment]
I would love to see a mini demo project which replicates this error systematically, so I could address it
