### ISSUE TITLE
NPE with Multipart request without file, notification config and required permissions

### ISSUE THREAD

**Issue by gotev** [gotev/android-upload-service#245]
### Version info
* Android Upload Service version: 3.2
* Android version and API version: 7 API 24
* HTTP stack (e.g. HurlStack or OkHttpStack): OkHttp

### What did you expect?
Successful request

### What happened instead?
Crash

### Request code:
```java
// android.permission.WRITE_EXTERNAL_STORAGE has not been requested at this point
private String upload(Context context, String uploadId, String endpoint) throws MalformedURLException {
    return new MultipartUploadRequest(context, uploadId, endpoint)
          .setMethod("POST")
          .setNotificationConfig(null)
          .setAutoDeleteFilesAfterSuccessfulUpload(true)
          .addParameter("color", "#ffffff")
          .setMaxRetries(2)
          .startUpload();
}
```
#### Where have you added the request code?
- [x] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String net.gotev.uploadservice.UploadNotificationConfig.getErrorMessage()' on a null object reference
      at net.gotev.uploadservice.UploadTask.broadcastError(UploadTask.java:413)
      at net.gotev.uploadservice.UploadTask.run(UploadTask.java:135)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
      at java.lang.Thread.run(Thread.java:761)
E/UploadStatusReceiver: Error in UploadId: net.gotev.uploadservice.UploadInfo@aed70be
      java.lang.RuntimeException: Please request android.permission.WRITE_EXTERNAL_STORAGE permission before performing the request! Check this: https://gist.github.com/gotev/67c300c563bdf68a502c
          at net.gotev.uploadservice.UploadTask.run(UploadTask.java:135)
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
          at java.lang.Thread.run(Thread.java:761)
```

**Comment by gotev** [comment]
After replicating the error and with the above the modifications, this is the output:
```java
D/UploadService: UploadRequest - setting provided upload ID
D/UploadService: UploadRequest - Created new upload request to http://posttestserver.com/post.php with ID: d1497088-2adc-438e-add9-17e2e986601e
I/UploadService: UploadService - Starting service with namespace: net.gotev.uploadservicedemo, upload pool size: 4, 1s idle thread keep alive time. Foreground execution is enabled
D/UploadService: UploadService - Successfully created new task with class: net.gotev.uploadservice.MultipartUploadTask
D/UploadService: HttpUploadTask - Starting upload task with ID d1497088-2adc-438e-add9-17e2e986601e
D/UploadService: OkHttpStackConnection - creating new connection
D/OkHttp: --> POST http://posttestserver.com/post.php http/1.1
D/OkHttp: Content-Type: multipart/form-data; boundary=-------AndroidUploadService1488564041697
D/OkHttp: Content-Length: 149
D/OkHttp: Connection: close
D/OkHttp: --> END POST
D/UploadService: UploadTask - Broadcasting upload progress for d1497088-2adc-438e-add9-17e2e986601e: 101 bytes of 149
D/OkHttp: <-- 200 OK http://posttestserver.com/post.php (1233ms)
D/OkHttp: Date: Fri, 03 Mar 2017 18:00:43 GMT
D/OkHttp: Server: Apache
D/OkHttp: Access-Control-Allow-Origin: *
D/OkHttp: Vary: Accept-Encoding
D/OkHttp: Connection: close
D/OkHttp: Content-Type: text/html; charset=UTF-8
D/OkHttp: <-- END HTTP
D/UploadService: HttpUploadTask - Server responded with HTTP 200 to upload with ID: d1497088-2adc-438e-add9-17e2e986601e
D/UploadService: UploadTask - Broadcasting upload completed for d1497088-2adc-438e-add9-17e2e986601e
D/UploadService: UploadService - All tasks finished. UploadService is about to shutdown...
D/UploadService: OkHttpStackConnection - closing connection
D/UploadService: UploadService - Stopping foreground execution
D/UploadService: UploadService - UploadService destroyed
```
The request is successful
