### ISSUE TITLE
java.lang.NoClassDefFoundError on android 4.4

### ISSUE THREAD

**Issue by AngleV** [gotev/android-upload-service#286]
Im getting this error on devices with android version 4.4

Stack Trace
-------------------------------
java.lang.NoClassDefFoundError: net.gotev.uploadservice.http.impl.HurlStack
	at net.gotev.uploadservice.UploadService.<clinit>(UploadService.java:68)
	at com.ic.beachsnapp.App.onCreate(App.java:86)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4893)
	at android.app.ActivityThread.access$1600(ActivityThread.java:174)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1385)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5756)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by gotev** [comment]
Are you using ProGuard?

**Comment by AngleV** [comment]
Yes !!!

**Comment by gotev** [comment]
You can use [this](https://github.com/gotev/android-upload-service/wiki/Advanced-topics#proguard) which is a little bit restrictive. Let me know if the issue is solved.

**Comment by gotev** [comment]
Improved [wiki](https://github.com/gotev/android-upload-service/wiki/Advanced-topics#proguard)
