### ISSUE TITLE
What about remaining upload failed images.?

### ISSUE THREAD

**Issue by rathoddeep** [gotev/android-upload-service#288]
Be sure to check [Asking for help](https://github.com/gotev/android-upload-service/wiki/Asking%20for%20help) page on the Wiki before opening a new issue! Delete this text when you create a new issue.

 

### What did you expect?
For eg. if i upload 5 images then image upload is started but in case of some network issue or whatever image uploading task is fail and out 5 2 image is not upload then what about remaining image and how can i know out of 5 which image is not upload. 
### What happened instead?
 currently happen those issue if in any situation some images is remain for upload then it can not restart upload of remaining images.

if i suddenly stop internet connectivity during image uploading then i am getting below log cat output which i mention  below:
### Library initialization code:
```java
// the code you wrote in your Application subclass here
 @Override
    protected void onResume() {
        // TODO Auto-generated method stub
        super.onResume();
        final IntentFilter intentFilter = new IntentFilter();
        intentFilter.addAction(UploadService.BROADCAST_ACTION);
        registerReceiver(uploadReceiver, intentFilter);

    }

    @Override
    protected void onPause() {
        super.onPause();
        unregisterReceiver(uploadReceiver);
    }


    private final BroadcastReceiver uploadReceiver = new AbstractUploadServiceReceiver() {

        @Override
        public void onProgress(int progress) {
            Log.e("AndroidUploadService", "DEEP The progress is: " + progress);
        }

        @Override
        public void onError(Exception exception) {
            Log.e("BAPU", "JITENDRA");
            Log.e("DEEP AndroidUpload", exception.getLocalizedMessage(), exception);
        }

        @Override
        public void onCompleted(int serverResponseCode, String serverResponseMessage, String serverResponseBody) {
            Log.e("AndroidUploadService", "DEEP Upload completed: " + serverResponseCode + ", " + serverResponseMessage);
        }

    };


### Request code:
```java
// the code you wrote to create the upload request
```
#### Where have you added the request code?
- [ ] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here

AndroidUpload: recvfrom failed: ECONNRESET (Connection reset by peer)
                                                                  java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
                                                                      at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:552)
                                                                      at libcore.io.IoBridge.recvfrom(IoBridge.java:516)
                                                                      at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
                                                                      at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
                                                                      at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
                                                                      at java.io.InputStream.read(InputStream.java:163)
                                                                      at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
                                                                      at java.io.BufferedInputStream.read(BufferedInputStream.java:227)
                                                                      at libcore.io.Streams.readAsciiLine(Streams.java:201)
                                                                      at libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:560)
                                                                      at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:813)
                                                                      at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:274)
                                                                      at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:486)
                                                                      at com.alexbbb.uploadservice.UploadService.handleFileUpload(UploadService.java:160)
                                                                      at com.alexbbb.uploadservice.UploadService.onHandleIntent(UploadService.java:121)
                                                                      at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                      at android.os.Looper.loop(Looper.java:137)
                                                                      at android.os.HandlerThread.run(HandlerThread.java:60)
                                                                   Caused by: libcore.io.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
                                                                      at libcore.io.Posix.recvfromBytes(Native Method)
                                                                      at libcore.io.Posix.recvfrom(Posix.java:131)
                                                                      at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)
                                                                      at libcore.io.IoBridge.recvfrom(IoBridge.java:513)
                                                                      at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488) 
                                                                      at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46) 
                                                                      at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240) 
                                                                      at java.io.InputStream.read(InputStream.java:163) 
                                                                      at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142) 
                                                                      at java.io.BufferedInputStream.read(BufferedInputStream.java:227) 
                                                                      at libcore.io.Streams.readAsciiLine(Streams.java:201) 
                                                                      at libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:560) 
                                                                      at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:813) 
                                                                      at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:274) 
                                                                      at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:486) 
                                                                      at com.alexbbb.uploadservice.UploadService.handleFileUpload(UploadService.java:160) 
                                                                      at com.alexbbb.uploadservice.UploadService.onHandleIntent(UploadService.java:121) 
                                                                      at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                      at android.os.Looper.loop(Looper.java:137) 
                                                                      at android.os.HandlerThread.run(HandlerThread.java:60) 

 
### Additional info
i am glad to use your library. i can use all functionality in you library but this issue just i can face so please give us solution ASAP.

 Thank you  so much in advance

**Comment by gotev** [comment]
As stated in https://github.com/gotev/android-upload-service/issues/235#issuecomment-277547987 multipart and binary uploads does not support resuming the upload. If something goes wrong, you have to start over, so the feature you described is simply not applicabile in this case, because even if 3 out of 5 files are successfully uploaded and then the connection drops, the server will discard automatically partial uploaded data. Server sees a multipart request as a single stream of data. Showing thw upload progress like that makes sense only for resumable uploads, like s3, google drive, one drive, tus or some other custom upload type.

**Comment by rathoddeep** [comment]
Hello there,
Thank you so much for you valuable reply, it means there is no other option for that issue.

**Comment by gotev** [comment]
Supporting resumable upload protocols is the next step of the library. Multipart is a well supported but old protocol, which does not suit modern needs and does not perform well on poor and dodgy networks. I only have to find the time to make the necessary implementations, because some architectural changes needs to be made to support them properly. One of those is request serialization.

**Comment by rathoddeep** [comment]
ok thank you but for my temporary solution can you just write code here for resumable upload.

**Comment by rathoddeep** [comment]
Hello There,
i just implement some code in your library and its completely working for resume failed image upload.

**Comment by gotev** [comment]
Wonderful! You can fork the main repo and add your modifications, so it will be available for other users too as a temporary solution!
