### ISSUE TITLE
Out of memory exception when trying to upload huge video file

### ISSUE THREAD

**Issue by VladislavNikolaev** [gotev/android-upload-service#289]
I've got OOME when was trying to upload a huge video file.

### Version info
* Android Upload Service version: 3.2.5
* Android version and API version: 7.0 API level 24
* HTTP stack (e.g. HurlStack or OkHttpStack): OkHttpStack 3.8.1

### What did you expect?
The file was uploaded to server using PUT Request

### What happened instead?
Crash with OOME

### Steps to reproduce (if applicable):
Upload huge file >=320Mb

### Library initialization code:
```java
    @Singleton
    @Provides
    static OkHttpClient provideOkHttpClient(
            @NonNull Cache cache,
            @NonNull OkLogInterceptor okLogInterceptor,
            @NonNull StethoInterceptor stethoInterceptor) {
        OkHttpClient client = newBaseOkHttpClient(cache, okLogInterceptor, stethoInterceptor)
                .build();
        UploadService.HTTP_STACK = new OkHttpStack(client);
        return client;
    }
```

### Request code:
```java
BinaryUploadRequest request = new BinaryUploadRequest(context, url)
                    .setFileToUpload(syncDbo.getFilePath())
                    .setMaxRetries(2)
                    .setMethod("PUT")
                    .setDelegate(uploadStatusSubscriber)
                    .startUpload();
```
#### Where have you added the request code?
- [ ] Activity
- [ ] Service
- [x] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
 Throwing OutOfMemoryError "Failed to allocate a 28 byte allocation with 0 free bytes and -1448B until OOM" (recursive case)
        "pool-6-thread-4" prio=5 tid=37 Runnable
          | group="main" sCount=0 dsCount=0 obj=0x12c0f790 self=0x707cfdfe00
          | sysTid=22687 nice=0 cgrp=default sched=0/0 handle=0x707c87c450
          | state=R schedstat=( 0 0 0 ) utm=68 stm=14 core=7 HZ=100
          | stack=0x707c77a000-0x707c77c000 stackSize=1037KB
          | held mutexes= "mutator lock"(shared held)
            at okio.Segment.<init>(Segment.java:63)
            at okio.SegmentPool.take(SegmentPool.java:48)
            at okio.Buffer.writableSegment(Buffer.java:1169)
            at okio.Buffer.write(Buffer.java:989)
            at okio.Buffer.write(Buffer.java:51)
            at net.gotev.uploadservice.okhttp.OkHttpBodyWriter.write(OkHttpBodyWriter.java:28)
            at net.gotev.uploadservice.http.BodyWriter.writeStream(BodyWriter.java:49)
            at net.gotev.uploadservice.BinaryUploadTask.onBodyReady(BinaryUploadTask.java:23)
            at net.gotev.uploadservice.okhttp.OkHttpStackConnection$1.writeTo(OkHttpStackConnection.java:107)
            at com.github.simonpercic.oklog3.LogDataInterceptor.writeRequestBody(LogDataInterceptor.java:124)
            at com.github.simonpercic.oklog3.LogDataInterceptor.writeRequestBody(LogDataInterceptor.java:25)
            at com.github.simonpercic.oklog.core.BaseLogDataInterceptor.processRequest(BaseLogDataInterceptor.java:119)
            at com.github.simonpercic.oklog3.OkLogInterceptor.intercept(OkLogInterceptor.java:43)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
            at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
            at okhttp3.RealCall.execute(RealCall.java:69)
            at net.gotev.uploadservice.okhttp.OkHttpStackConnection.getResponse(OkHttpStackConnection.java:117)
            at net.gotev.uploadservice.HttpUploadTask.upload(HttpUploadTask.java:70)
            at net.gotev.uploadservice.UploadTask.run(UploadTask.java:137)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
            at java.lang.Thread.run(Thread.java:762)
```

**Comment by VladislavNikolaev** [comment]
Sorry, it was my fault, i was trying to upload some huge files in parallel, fixed it by sequenced upload. 
Closing this issue.

**Comment by haneef5k** [comment]
@VladislavNikolaev can share your code..i want to know, how to implement sequenced  upload.
