### ISSUE TITLE
ConcurrentModificationException in FTPUploadTask

### ISSUE THREAD

**Issue by shobra** [gotev/android-upload-service#310]
### What did you expect?
Upload files without the need for retrying.
### What happened instead?
No matter whether I try to upload one or multiple files using the `FTPUploadRequest`, the first attempt of an upload always fails due to this exception. With multiple files, this leads to an increasing number of retries (one for each file), causing the upload to hang (because of the retry wait time growth) and ultimately fail once the file count reaches the retry limit. 
### Version info
* Android Upload Service version: 3.4
* compileSdkVersion: 26
* buildToolsVersion: 26.0.1
* HTTP stack (e.g. HurlStack or OkHttpStack): OkHttpStack

### Library initialization code:
```java
UploadService.NAMESPACE = BuildConfig.APPLICATION_ID;
UploadService.HTTP_STACK = new OkHttpStack();
Logger.setLogLevel(Logger.LogLevel.DEBUG);
```

### Request code:
```java
try {
	FTPUploadRequest uploadRequest = new FTPUploadRequest(context, FileUtil.FTP_SERVER_URL, FileUtil.FTP_SERVER_PORT)
			.setUsernameAndPassword(FileUtil.FTP_USERNAME_DEFAULT, FileUtil.FTP_PASSWORD_DEFAULT)
			.setNotificationConfig(new UploadNotificationConfig())
			.useCompressedFileTransferMode(true)
			.setMaxRetries(100);
	for (StoredDocument document :
			documents) {
		uploadRequest.addFileToUpload(document.filePath, FileUtil.localToRemotePath(document.filePath));
	}
	String uploadId = uploadRequest.setDelegate(new UploadStatusDelegate() {
		@Override
		public void onProgress(Context context, UploadInfo uploadInfo) {
			// ...
		}

		@Override
		public void onError(Context context, UploadInfo uploadInfo, ServerResponse serverResponse, Exception exception) {
			// ...
		}

		@Override
		public void onCompleted(Context context, UploadInfo uploadInfo, ServerResponse serverResponse) {
			// ...
		}

		@Override
		public void onCancelled(Context context, UploadInfo uploadInfo) {
			// ...
		}
	}).startUpload();
} catch (Exception exc) {
	Log.e("AndroidUploadService", exc.getMessage(), exc);
}
```
#### Where have you added the request code?
A presenter attached to an activity.

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
08-28 20:46:36.496 17787-17787/net.gotev.uploadservicedemo D/UploadService: UploadRequest - setting provided upload ID
08-28 20:46:36.501 17787-17787/net.gotev.uploadservicedemo D/UploadService: UploadRequest - Created new upload request to *** with ID: 4c0d05a9-4664-4e09-b89c-a8f645a2514c
08-28 20:46:36.593 17787-17787/net.gotev.uploadservicedemo I/UploadService: UploadService - Starting service with namespace: net.gotev.uploadservicedemo, upload pool size: 8, 5s idle thread keep alive time. Foreground execution is enabled
08-28 20:46:36.601 17787-17787/net.gotev.uploadservicedemo D/UploadService: UploadService - Successfully created new task with class: net.gotev.uploadservice.ftp.FTPUploadTask
08-28 20:46:36.615 17787-19545/net.gotev.uploadservicedemo D/UploadService: UploadService - 4c0d05a9-4664-4e09-b89c-a8f645a2514c now holds the foreground notification
08-28 20:46:36.667 17787-19545/net.gotev.uploadservicedemo D/UploadService: FTPUploadTask - Connect timeout set to 5000ms
08-28 20:46:36.667 17787-19545/net.gotev.uploadservicedemo D/UploadService: FTPUploadTask - Connecting to *** as ***
08-28 20:46:36.703 17787-17787/net.gotev.uploadservicedemo W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
08-28 20:46:36.716 17787-17806/net.gotev.uploadservicedemo D/OpenGLRenderer: endAllActiveAnimators on 0x7f890d1000 (RippleDrawable) with handle 0x7f89e242e0
08-28 20:46:36.924 17787-19545/net.gotev.uploadservicedemo D/UploadService: FTPUploadTask - Socket timeout set to 5000ms. Enabled control keep alive every 2s
08-28 20:46:37.059 17787-19545/net.gotev.uploadservicedemo D/UploadService: FTPUploadTask - FTP default working directory is: /
08-28 20:46:37.060 17787-19545/net.gotev.uploadservicedemo D/UploadService: FTPUploadTask - Starting FTP upload of: ***.pdf to: test1.pdf
08-28 20:46:37.223 17787-19545/net.gotev.uploadservicedemo D/UploadService: UploadTask - Broadcasting upload progress for 4c0d05a9-4664-4e09-b89c-a8f645a2514c: 917 bytes of 1834
08-28 20:46:37.330 17787-19545/net.gotev.uploadservicedemo D/UploadService: FTPUploadTask - Logout and disconnect from FTP server: ***:21
08-28 20:46:37.392 17787-19545/net.gotev.uploadservicedemo E/UploadService: UploadTask - Error in uploadId 4c0d05a9-4664-4e09-b89c-a8f645a2514c on attempt 1. Waiting 1s before next attempt. 
                                                                            java.util.ConcurrentModificationException
                                                                                at java.util.ArrayList$Itr.remove(ArrayList.java:846)
                                                                                at net.gotev.uploadservice.ftp.FTPUploadTask.upload(FTPUploadTask.java:122)
                                                                                at net.gotev.uploadservice.UploadTask.run(UploadTask.java:136)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                at java.lang.Thread.run(Thread.java:761)
08-28 20:46:39.393 17787-19545/net.gotev.uploadservicedemo D/UploadService: FTPUploadTask - Connect timeout set to 5000ms
08-28 20:46:39.393 17787-19545/net.gotev.uploadservicedemo D/UploadService: FTPUploadTask - Connecting to ***:21 as ***
08-28 20:46:39.632 17787-19545/net.gotev.uploadservicedemo D/UploadService: FTPUploadTask - Socket timeout set to 5000ms. Enabled control keep alive every 2s
08-28 20:46:39.761 17787-19545/net.gotev.uploadservicedemo D/UploadService: FTPUploadTask - FTP default working directory is: /
08-28 20:46:39.762 17787-19545/net.gotev.uploadservicedemo D/UploadService: FTPUploadTask - Starting FTP upload of: ***.pdf to: test2.pdf
08-28 20:46:39.905 17787-19545/net.gotev.uploadservicedemo D/UploadService: UploadTask - Broadcasting upload progress for 4c0d05a9-4664-4e09-b89c-a8f645a2514c: 1834 bytes of 1834
08-28 20:46:40.010 17787-19545/net.gotev.uploadservicedemo D/UploadService: FTPUploadTask - Logout and disconnect from FTP server: ***:21
08-28 20:46:40.053 17787-19545/net.gotev.uploadservicedemo E/UploadService: UploadTask - Error in uploadId 4c0d05a9-4664-4e09-b89c-a8f645a2514c on attempt 2. Waiting 2s before next attempt. 
                                                                            java.util.ConcurrentModificationException
                                                                                at java.util.ArrayList$Itr.remove(ArrayList.java:846)
                                                                                at net.gotev.uploadservice.ftp.FTPUploadTask.upload(FTPUploadTask.java:122)
                                                                                at net.gotev.uploadservice.UploadTask.run(UploadTask.java:136)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                at java.lang.Thread.run(Thread.java:761)
08-28 20:46:42.055 17787-19545/net.gotev.uploadservicedemo D/UploadService: FTPUploadTask - Connect timeout set to 5000ms
08-28 20:46:42.055 17787-19545/net.gotev.uploadservicedemo D/UploadService: FTPUploadTask - Connecting to ***:21 as ***
08-28 20:46:42.306 17787-19545/net.gotev.uploadservicedemo D/UploadService: FTPUploadTask - Socket timeout set to 5000ms. Enabled control keep alive every 2s
08-28 20:46:42.434 17787-19545/net.gotev.uploadservicedemo D/UploadService: FTPUploadTask - FTP default working directory is: /
08-28 20:46:42.434 17787-19545/net.gotev.uploadservicedemo D/UploadService: UploadTask - Broadcasting upload completed for 4c0d05a9-4664-4e09-b89c-a8f645a2514c
08-28 20:46:42.460 17787-19545/net.gotev.uploadservicedemo D/UploadService: UploadService - 4c0d05a9-4664-4e09-b89c-a8f645a2514c now un-holded the foreground notification
08-28 20:46:42.460 17787-19545/net.gotev.uploadservicedemo D/UploadService: UploadService - All tasks completed, stopping foreground execution
08-28 20:46:42.464 17787-19545/net.gotev.uploadservicedemo I/UploadService: UploadService - Service will be shut down in 10000ms if no new tasks are received
08-28 20:46:42.467 17787-19545/net.gotev.uploadservicedemo D/UploadService: FTPUploadTask - Logout and disconnect from FTP server: ***:21
08-28 20:46:52.468 17787-19598/net.gotev.uploadservicedemo I/UploadService: UploadService - Service is about to be stopped because idle timeout of 10000ms has been reached
08-28 20:46:52.470 17787-17787/net.gotev.uploadservicedemo D/UploadService: UploadService - Stopping foreground execution
08-28 20:46:52.473 17787-17787/net.gotev.uploadservicedemo D/UploadService: UploadService - UploadService destroyed
```

### Server side
Own server.

### Additional info
This happens both in my app and the uploadservice-demo-debug.apk. The above logcat is from the demo app with two files added.

**Comment by vincentsong** [comment]
I got same problem, any plan to fix it?

**Comment by gotev** [comment]
So it's not an isolated case. @vincentsong a PR will greatly speed up the process
