### ISSUE TITLE
OutofMemory Exception is happening

### ISSUE THREAD

**Issue by droidluv** [gotev/android-upload-service#334]
### What did you expect?
No crash from the service

### What happened instead?
The service crashed

### Version info
* Android Upload Service version: 3.4
* Android version and API version: 7.1.2(26), 7.1.1(26)
* HTTP stack (e.g. HurlStack or OkHttpStack):

### Steps to reproduce (if applicable):
An upload of nearly 250Mb video at 571Mbit/sec

### Library initialization code:
```java
// the code you wrote in your Application subclass here
```
UploadService.NAMESPACE = BuildConfig.APPLICATION_ID
  UploadService.HTTP_STACK = OkHttpStack(okHttpClient)
### Request code:
```java
// the code you wrote to create the upload request
```
val uploadNotificationConfig = UploadNotificationConfig()
                .setNotificationChannelId(NOTIFICATION_CHANNEL_ID)
                .setTitleForAllStatuses("Video Upload")
                .setClearOnActionForAllStatuses(true)

        val topActivityIntent = Intent(context, ApplyToBeTrainerActivity::class.java)
        topActivityIntent.putExtra("videoUploadError", 0)
        topActivityIntent.putExtra("showVideoUploadScreen", true)
        topActivityIntent.putExtra("accessToken", accessToken)
        topActivityIntent.putExtra("path", path)
        topActivityIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        val errorPendingIntent = PendingIntent.getActivity(context, 23, topActivityIntent, PendingIntent.FLAG_UPDATE_CURRENT)
        uploadNotificationConfig.error.clickIntent = errorPendingIntent
        uploadNotificationConfig.cancelled.clickIntent = errorPendingIntent

        MultipartUploadRequest(context, VIDEO_UPLOAD_URL)
                .addFileToUpload(path, "video")
                .addHeader("Authorization", "Bearer " + accessToken)
                .setNotificationConfig(uploadNotificationConfig)
                .setMaxRetries(2)
                .startUpload()

#### Where have you added the request code?
- [ ] Activity
- [ ] Service
- [x] Other class (add additional info about it)

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)

11-16 20:34:19.843 16134-19041/com.handstandapp.trainerteam E/AndroidRuntime: FATAL EXCEPTION: pool-9-thread-1
                                                                              Process: com.handstandapp.trainerteam, PID: 16134
                                                                              java.lang.OutOfMemoryError: Failed to allocate a 8204 byte allocation with 1536 free bytes and 1536B until OOM
                                                                                  at okio.Segment.<init>(Segment.java:63)
                                                                                  at okio.SegmentPool.take(SegmentPool.java:48)
                                                                                  at okio.Buffer.writableSegment(Buffer.java:1169)
                                                                                  at okio.Buffer.write(Buffer.java:989)
                                                                                  at okio.Buffer.write(Buffer.java:51)
                                                                                  at net.gotev.uploadservice.okhttp.OkHttpBodyWriter.write(OkHttpBodyWriter.java:28)
                                                                                  at net.gotev.uploadservice.http.BodyWriter.writeStream(BodyWriter.java:51)
                                                                                  at net.gotev.uploadservice.MultipartUploadTask.writeFiles(MultipartUploadTask.java:141)
                                                                                  at net.gotev.uploadservice.MultipartUploadTask.onBodyReady(MultipartUploadTask.java:66)
                                                                                  at net.gotev.uploadservice.okhttp.OkHttpStackConnection$1.writeTo(OkHttpStackConnection.java:107)
                                                                                  at com.readystatesoftware.chuck.ChuckInterceptor.intercept(ChuckInterceptor.java:154)
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                  at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                                                  at okhttp3.RealCall.execute(RealCall.java:69)
                                                                                  at net.gotev.uploadservice.okhttp.OkHttpStackConnection.getResponse(OkHttpStackConnection.java:117)
                                                                                  at net.gotev.uploadservice.HttpUploadTask.upload(HttpUploadTask.java:72)
                                                                                  at net.gotev.uploadservice.UploadTask.run(UploadTask.java:154)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                  at java.lang.Thread.run(Thread.java:762)
```
// your LogCat output here
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?

```
// your server side script (if applicable)
// do not write any passwords or personal data here.
// If you need to show some code, replace sensible values
```

#### Server log (if applicable)
```
// your server side log here
```

### Additional info
Write some additional information about the error here. Upload also screenshots or other information which may help to reproduce your error or spot a possible bug. Thank you :)

**Comment by gotev** [comment]
Do you send big payload as a response of the upload from the server?

**Comment by droidluv** [comment]
No the response never came, the upload went upto like 50 percent and then crashed, also for smaller files the crash is not happening.

**Comment by droidluv** [comment]
Could it be because of chuck https://github.com/jgilfelt/chuck it's a really convenient interceptor which I use with okhttp in my test builds.

**Comment by gotev** [comment]
Yes, because the payload you sent gets cached entirely by chuck. The same happens if you use the Okttp Http Logging Interceptor with BODY level. Basically, to be able to show you what's passing on the wire, everything gets cached. Loggin interceptors usually warns you that you're going to have problems tracking huge payloads.
