### ISSUE TITLE
FileNotFoundException on certain cases ?

### ISSUE THREAD

**Issue by guffyWave** [gotev/android-upload-service#336]
### 
Encountering FileNotFoundException  when UploadService is trying . There is a picture we have camera captured and copies it to internal memory of app .The objective is to upload that internally stored file.I have already checked physical existence of file.

### Query
* I would like to know how android-upload-service takes care of 0 byte file ?
* As the discussed  [here](https://stackoverflow.com/questions/19307622/java-new-file-says-filenotfoundexception-but-file-exists), can there be a case when Android OS rejects file read operation and canRead() method retruns false ?

### Version info
* Android Upload Service version: 3.0
* Android version and API version: Android 4,5,6,7 and API Level 23

### Request code:
```
  MultipartUploadRequest req = new MultipartUploadRequest(context, fileUploadTask.getMediaServerURL().getServerURL())
                        .addFileToUpload(fileUploadTask.getFile().getAbsolutePath(), getUploadKeyBasedOnFileType(fileUploadTask))
                      .setAutoDeleteFilesAfterSuccessfulUpload(AUTO_DELETE_FILES_AFTER_SUCCESSFULL_UPLOAD)
                        .setNotificationConfig(getNotificationConfig(fileUploadTask.getFile().getName()))
                        .setUsesFixedLengthStreamingMode(true)
                        .setMaxRetries(MAX_RETRIES);
                String uploadID = req.startUpload();

```
### Stack Trace 
```
Non-fatal Exception: java.io.FileNotFoundException: Could not find file at path: /data/user/0/in.oku.brofirst/files/1511248311838.jpg
       at net.gotev.uploadservice.UploadFile.(SourceFile)
       at net.gotev.uploadservice.MultipartUploadRequest.addFileToUpload(SourceFile:82)
       at net.gotev.uploadservice.MultipartUploadRequest.addFileToUpload(SourceFile:148)
       at in.oku.brofirst.services.uploadservice.FileUploadManager.retryTask(SourceFile:94)
       at in.oku.brofirst.services.uploadservice.FileUploadManager.forceSync(SourceFile:124)
       at in.oku.brofirst.services.uploadservice.util.NetworkChangeReceiver.onReceive(SourceFile:45)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3061)
       at android.app.ActivityThread.-wrap18(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1590)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6237)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

 Thank you :)

**Comment by gotev** [comment]
No check are made to detect if a file has zero length, but it will be good to have it.

Regarding the FileNotFoundException, check that the path to the file is trimmed, accessible to your app (you have storage read and write permissions). Ensure all other previous writes to the file are finished prior to starting the upload (e.g. you take a photo and then upload it. Be sure the write process has terminated before starting the upload).
