### ISSUE TITLE
add config for set protocol(android < 5)

### ISSUE THREAD

**Issue by rasoulinejad** [gotev/android-upload-service#366]
server not support sslv3
Protocols
TLS 1.3 | No
TLS 1.2 | Yes
TLS 1.1 | Yes
TLS 1.0 | Yes
SSL 3 | No

Android: 4.3
Manufacturer: samsung
Model: GT-I9300I

javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x656b92c0: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x5ad1bc8c:0x00000000)
	at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:440)
	at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:209)
	at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
	at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:442)
	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290)
	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
	at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:81)
	at libcore.net.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
	at libcore.net.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:281)
	at net.gotev.uploadservice.http.impl.HurlStackConnection.getResponse(HurlStackConnection.java:144)
	at net.gotev.uploadservice.HttpUploadTask.upload(HttpUploadTask.java:72)
	at net.gotev.uploadservice.UploadTask.run(UploadTask.java:155)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

**Comment by gotev** [comment]
This is a bug with older devices which simply does not support (and never will) TLS 1.3. It's an Android networking problem, independent of the library.

**Comment by AlbertoMrFz** [comment]
I have the same issue.
In samsung galaxy note III with android 4.4.2 And in samsung galaxy s6 with android 7

How i can solve them?

**Comment by gotev** [comment]
Same as #376
