### ISSUE TITLE
Android Oreo Background still has  Limitations 

### ISSUE THREAD

**Issue by salamgithub2017** [gotev/android-upload-service#369]
### What did you expect?
i expect problem be solved for 3.4.2

### What happened instead?
app still crash. and i have another service as JobService but still crash on that

### Version info
* Android Upload Service version 3.4.2:
* Android version and API version 26:

### Request code:
```java

                final String url = *******;
                Utils.runOnUIThread(new Runnable() {
                    @Override
                    public void run() {
                        try {
                            new MultipartUploadRequest(ServiceSendImage.this, url)
                                    .addFileToUpload(imagePath,"Signature")
                                    .addParameter("A",String.valueOf(mySharedPreference.getA()))
                                    .addParameter("B",mySharedPreference.getB())
                                    .addParameter("C", mySharedPreference.getC())
                                    .setUtf8Charset()
                                    .setMethod("POST")
                                    .setDelegate(ServiceSendImage.this)
                                    .startUpload();
                         
                        } catch (MalformedURLException e) {
                            e.printStackTrace();
                        } catch (FileNotFoundException e) {
                            e.printStackTrace();
                        }
                    }
                });
 Where have you added the request code?

 Service


### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
 java.lang.IllegalArgumentException: Android Oreo requires a notification configuration for the service to run. https://developer.android.com/reference/android/content/Context.html#startForegroundService(android.content.Intent)
                                         at net.gotev.uploadservice.UploadRequest.startUpload(UploadRequest.java:72)
                                         at com.example.Services.ServiceSendImage$1.run(ServiceSendImage.java:87)
                                         at android.os.Handler.handleCallback(Handler.java:789)
                                         at android.os.Handler.dispatchMessage(Handler.java:98)
                                         at android.os.Looper.loop(Looper.java:164)
                                         at android.app.ActivityThread.main(ActivityThread.java:6541)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by gotev** [comment]
The solution is in the first message of the stack trace. You just need to add a notification config in the request. It's also strage to see the service invocation from an UI thread. You can safely invoke it from the background.
