### ISSUE TITLE
java.net.SocketTimeoutException 

### ISSUE THREAD

**Issue by vicmns** [gotev/android-upload-service#417]
I'm getting `java.net.SocketTimeoutException` in my crashlytics from time to time. What is strange if I look at the stack trace it looks like all exceptions are being caught. But again I'm getting the exception...
### Version info
* Android Upload Service version: 3.4.2
* Android version and API version:
* HTTP stack (e.g. HurlStack or OkHttpStack): OkHttpStack

### Library initialization code:
```kotlin
UploadService.NAMESPACE = BuildConfig.APPLICATION_ID
UploadService.HTTP_STACK = OkHttpStack(okHttpClient)
if (BuildConfig.DEBUG) {
   Logger.setLogLevel(Logger.LogLevel.DEBUG)
}
```

### Request code:
```kotlin
val uploadRequest = MultipartUploadRequest(context, baseUrlHolder.getUploadUrl())
                .setNotificationConfig(getNotificationConfig(context))
                .setMaxRetries(3)
                .setDelegate(delegate)
contracts.forEach {
    uploadRequest.addFileToUpload(it.fileUri.toString(), "file")
}
try {
    return uploadRequest.startUpload()
} catch (exc: Exception) {
    
}

return null
```
#### Where have you added the request code?
- Service

### LogCat output
```
Non-fatal Exception: java.net.SocketTimeoutException: timeout
       at okio.Okio$4.newTimeoutException(Okio.java:230)
       at okio.AsyncTimeout.exit(AsyncTimeout.java:275)
       at okio.AsyncTimeout$1.write(AsyncTimeout.java:186)
       at okio.RealBufferedSink.flush(RealBufferedSink.java:216)
       at okhttp3.internal.http1.Http1Codec$FixedLengthSink.flush(Http1Codec.java:298)
       at okio.ForwardingSink.flush(ForwardingSink.java:39)
       at okio.RealBufferedSink.flush(RealBufferedSink.java:218)
       at net.gotev.uploadservice.okhttp.OkHttpBodyWriter.flush(OkHttpBodyWriter.java:33)
       at net.gotev.uploadservice.http.BodyWriter.writeStream(BodyWriter.java:52)
       at net.gotev.uploadservice.MultipartUploadTask.writeFiles(MultipartUploadTask.java:143)
       at net.gotev.uploadservice.MultipartUploadTask.onBodyReady(MultipartUploadTask.java:66)
       at net.gotev.uploadservice.okhttp.OkHttpStackConnection$1.writeTo(OkHttpStackConnection.java:107)
       at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at mx.sahuaro.prosesatim.net.retrofit.BasicAuthInterceptor.intercept(BasicAuthInterceptor.kt:32)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
       at okhttp3.RealCall.execute(RealCall.java:77)
       at net.gotev.uploadservice.okhttp.OkHttpStackConnection.getResponse(OkHttpStackConnection.java:117)
       at net.gotev.uploadservice.HttpUploadTask.upload(HttpUploadTask.java:72)
       at net.gotev.uploadservice.UploadTask.run(UploadTask.java:155)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```

**Comment by vicmns** [comment]
Nop, wouldn't the Builder provide a default value for each one?

**Comment by vicmns** [comment]
Looking at the OkHttpClient.Builder class indeed it has default values:
```java
connectTimeout = 10_000;
readTimeout = 10_000;
writeTimeout = 10_000;
```

**Comment by gotev** [comment]
Check if those values work for you. Usually expliciting them is better. Problems of this kind are unrelated to this library and usually come from custom interceptors without socket error handling. See this for your basic auth interceptor: https://stackoverflow.com/questions/29921667/retrofit-and-okhttpclient-catch-connection-timeout-in-failure-method
