### ISSUE TITLE
Getting Security Exception

### ISSUE THREAD

**Issue by Sunaina015** [gotev/android-upload-service#433]
android.media.RingtoneManager.getActualDefaultRingtoneUri (RingtoneManager.java:927)
**net.gotev.uploadservice.UploadTask.setRingtone (UploadTask.java:512)** (On this line)
net.gotev.uploadservice.UploadTask.updateNotification (UploadTask.java:540)
net.gotev.uploadservice.UploadTask.broadcastError (UploadTask.java:419)
net.gotev.uploadservice.UploadTask.run (UploadTask.java:162)

**Comment by gotev** [comment]
Please fill in the complete issue template providing more context to replicate this error

**Comment by Sunaina015** [comment]
Fatal Exception: java.lang.SecurityException: Permission Denial: getCurrentUser() from pid=6068, uid=10467 requires android.permission.INTERACT_ACROSS_USERS
       at android.os.Parcel.readException(Parcel.java:1599)
       at android.os.Parcel.readException(Parcel.java:1552)
       at android.app.ActivityManagerProxy.getCurrentUser(ActivityManagerNative.java:5229)
       at android.app.ActivityManager.getCurrentUser(ActivityManager.java:2755)
       at android.media.RingtoneManager.getActualDefaultRingtoneUri(RingtoneManager.java:1245)
       at android.media.RingtoneManager.getActualDefaultRingtoneUri(RingtoneManager.java:927)
       at net.gotev.uploadservice.UploadTask.setRingtone(UploadTask.java:512)
       at net.gotev.uploadservice.UploadTask.updateNotification(UploadTask.java:540)
       at net.gotev.uploadservice.UploadTask.broadcastError(UploadTask.java:419)
       at net.gotev.uploadservice.UploadTask.run(UploadTask.java:162)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by gotev** [comment]
This is the issue template: https://github.com/gotev/android-upload-service/blob/master/ISSUE_TEMPLATE.md

I need you to fill in all the required data to help you

**Comment by gotev** [comment]
With the data posted here the only advice I can give is to ask for that permission in your app before you make an upload.
