### ISSUE TITLE
Upload is failed for some files

### ISSUE THREAD

**Issue by minamak91** [gotev/android-upload-service#548]
**Describe the bug**
Upload failed with `UploadError` exception with some files.

**To Reproduce**
Just upload a file, but it happens randomly...

**Expected behavior**
The app doesn't return `UploadError` Exception

**Screenshots**
This the stack trace and the logs
```
    java.net.ProtocolException: expected 2637 bytes but received 3028
        at com.android.okhttp.internal.http.Http1xStream$FixedLengthSink.write(Http1xStream.java:287)
        at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:222)
        at com.android.okhttp.okio.RealBufferedSink$1.flush(RealBufferedSink.java:205)
        at net.gotev.uploadservice.network.hurl.HurlBodyWriter.flush(HurlBodyWriter.kt:21)
        at net.gotev.uploadservice.network.BodyWriter.write(BodyWriter.kt:67)
        at net.gotev.uploadservice.network.BodyWriter.writeStream(BodyWriter.kt:42)
        at net.gotev.uploadservice.protocols.multipart.MultipartUploadTask.writeFiles(MultipartUploadTask.kt:52)
        at net.gotev.uploadservice.protocols.multipart.MultipartUploadTask.onWriteRequestBody(MultipartUploadTask.kt:81)
        at net.gotev.uploadservice.network.hurl.HurlStackRequest.getResponse(HurlStackRequest.kt:112)
        at net.gotev.uploadservice.HttpUploadTask.upload(HttpUploadTask.kt:49)
        at net.gotev.uploadservice.UploadTask.run(UploadTask.kt:140)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
    	Suppressed: java.net.ProtocolException: expected 2637 bytes but received 3028
        at com.android.okhttp.internal.http.Http1xStream$FixedLengthSink.write(Http1xStream.java:287)
        at com.android.okhttp.okio.RealBufferedSink.close(RealBufferedSink.java:235)
        at com.android.okhttp.okio.RealBufferedSink$1.close(RealBufferedSink.java:210)
        at net.gotev.uploadservice.network.hurl.HurlBodyWriter.close(HurlBodyWriter.kt:26)
        at kotlin.io.CloseableKt.closeFinally(Closeable.kt:60)
        at net.gotev.uploadservice.network.hurl.HurlStackRequest.getResponse(HurlStackRequest.kt:111)
```

```
"uploadServiceVersion": "4.4.1",
        "androidApiVersion": 29,
        "namespace": "de.pharossolutions.drawneat.freelancer.debug",
        "deviceProcessors": 4,
        "idleTimeoutSeconds": 10,
        "bufferSizeBytes": 4096,
        "httpStack": "net.gotev.uploadservice.network.hurl.HurlStack",
        "uploadProgressNotificationIntervalMillis": 333,
        "retryPolicy": {"initialWaitTimeSeconds": 1, "maxWaitTimeSeconds": 100, "multiplier": 2, "defaultMaxRetries": 3},
        "isForegroundService": true,
        "schemeHandlers": {"/": "net.gotev.uploadservice.schemehandlers.FileSchemeHandler", "content://": "net.gotev.uploadservice.schemehandlers.ContentResolverSchemeHandler"}
    }
```

**OS and Lib versions (please complete the following information):**
- Android Upload Service version: 4.4.1
- Android version and API version: 29

**Debug Log**:
```
2020-12-20 18:44:53.937 3749-4177/de.pharossolutions.drawneat.freelancer.debug I/UploadService: MultipartUploadTask - (uploadId: 28a6b4cc-3e05-4b21-9eb2-ff5dd5042230) - Starting upload task
2020-12-20 18:44:53.961 3749-4177/de.pharossolutions.drawneat.freelancer.debug I/UploadService: HurlStackRequest - (uploadId: 28a6b4cc-3e05-4b21-9eb2-ff5dd5042230) - creating new HttpURLConnection (uuid: ee0bf8d4-e388-4b33-965b-b038bed87a8c)
2020-12-20 18:44:54.463 3749-4177/de.pharossolutions.drawneat.freelancer.debug I/UploadService: UploadTask - (uploadId: 28a6b4cc-3e05-4b21-9eb2-ff5dd5042230) - uploaded 0%, 113 of 247355 bytes
2020-12-20 18:44:54.511 3749-4177/de.pharossolutions.drawneat.freelancer.debug I/UploadService: HurlStackRequest - (uploadId: 28a6b4cc-3e05-4b21-9eb2-ff5dd5042230) - closing HttpURLConnection (uuid: ee0bf8d4-e388-4b33-965b-b038bed87a8c)
```

**Comment by gotev** [comment]
Thanks for reporting this. After some checks, it's not a library issue. Be sure the content of the file is not changing while you are uploading it. This is why the ProtocolException is fired.

**Comment by minamak91** [comment]
@gotev I did some investigations and didn't find how the file content is changed during the uploading. The uploading is just started using `MultipartUploadRequest` and I'm just getting the progress and wait until the file is finished. Note that this issue only happens with images with some devices not all of them. Can you please do some investigations?

**Comment by gotev** [comment]
Ok so can you please make a test which replicates the case? You can look at the existing ones as a starting point. I bet it would not be easy to replicate, but that's the point. We should cause the issue to happen systematically before doing anything else. Currently I have no evidence of a bug by looking at the code. Moreover, this lib is a convenient wrapper on top standard HTTP stacks to upload stuff. We should at least find if it's a lib problem or an HTTP stack problem, to eventually report the problem to other communities with clear evidence. By searching the same issue on the net I found it also happens with Retrofit, OkHttp and HttpURLConnection under certain circumstances. The main cause is the file getting modified while it's being uploaded and many people out there suggest to make a copy of the file and then upload it. It seems a hack to me btw.

From a protocol point of view, the file size is computed at the start of the upload and the content length header gets sent to the server. Then, the file stream gets open and the bytes transferred. If the total size transferred is different from the originally computed size, you get that error.

**Comment by minamak91** [comment]
@gotev Thank you so much for the explanation. I will try to create a repo that reproduces the issue and give it to you so you can give me an assist.
I found now that only the images that I have captured using the camera have this issue. If an image is downloaded from the browser of the mobile, it works fine.
I will create the repo and get back to you. Thank you so much

**Comment by gotev** [comment]
@minamak91 this leads me to the thought that maybe the specific camera app retains (or leaks) some reference to the file and eventually modifies it afterwards. It could not be a problem of this lib or even the HTTP stacks, but the camera app itself. We'll see once we get some real scenarios replicated 😉 

In the existing tests you'll find `assertDeclaredContentLengthMatchesPostBodySize` which is an extension function that verifies initial request size (file size for binary and file size + protocol overhead for multipart) against actually transferred bytes size. As a starting point I think the best is to simulate a file which is being modified while it's being uploaded in the tests, to trigger the above mentioned exception or to fail the `assertDeclaredContentLengthMatchesPostBodySize`. This way we'll have a systematical proof that it happens in that specific case.

Reopened the issue.

**Comment by minamak91** [comment]
@gotev After some investigations, I found that It only happens on the emulator, not the real devices so I think it's not important anymore for me. Thank you for your time & sorry for the interruption.

**Comment by gotev** [comment]
Ok then, closing this for now as to me it's just an external app's bug from the evidence and data I have at this moment. Anyone reading this and wishing to make an automated test for this particular case is welcome to create a PR directly and mention this isse 😉
