### ISSUE TITLE
Sending request without attached file causes java.io.EOFException

### ISSUE THREAD

**Issue by EngKhAboshama** [gotev/android-upload-service#552]
Please I have an issue with the uploading "HttpUploadTask". My request params contain optional uploading files. I want to use the service with empty files just only my extra params. I'm using "startUpload()" inside abstract class "UploadRequest". 

If I use the above functions, the error displays in the logcat  
UploadTask - (uploadId: 533c29e9-d3f1-4dbe-9faf-4744b62e5ef0) - error
    java.io.EOFException: \n not found: size=1 content=0d...
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:202)
        at com.android.okhttp.internal.http.Http1xStream.readHeaders(Http1xStream.java:213)
        at com.android.okhttp.internal.http.Http1xStream$ChunkedSource.readChunkSize(Http1xStream.java:467)
        at com.android.okhttp.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:437)
        at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:51)
        at com.android.okhttp.okio.RealBufferedSource.exhausted(RealBufferedSource.java:61)
        at com.android.okhttp.okio.GzipSource.read(GzipSource.java:101)
        at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:372)
        at java.io.InputStream.read(InputStream.java:101)
        at kotlin.io.ByteStreamsKt.copyTo(IOStreams.kt:110)
        at kotlin.io.ByteStreamsKt.copyTo$default(IOStreams.kt:103)
        at kotlin.io.ByteStreamsKt.readBytes(IOStreams.kt:136)
        at net.gotev.uploadservice.network.hurl.HurlStackRequest.getResponseBody(HurlStackRequest.kt:62)
        at net.gotev.uploadservice.network.hurl.HurlStackRequest.getResponse(HurlStackRequest.kt:115)
        at net.gotev.uploadservice.HttpUploadTask.upload(HttpUploadTask.kt:49)
        at net.gotev.uploadservice.UploadTask.run(UploadTask.kt:140)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

 Thank you in advance

**Comment by gotev** [comment]
The library is not designed for optional files. Also, you should be using Multipart or Binary request builders instead of HttpUploadRequest which is a type to be used only internally.
