### ISSUE TITLE
Request success with the error exception  

### ISSUE THREAD

**Issue by EngKhAboshama** [gotev/android-upload-service#553]
I'm uploading files using the "startUpload" and the response = 200 with error exception. Please I want to know what is wrong in this?

java.io.IOException: closed
        at com.android.okhttp.okio.RealBufferedSource$1.available(RealBufferedSource.java:380)
        at kotlin.io.ByteStreamsKt.readBytes(IOStreams.kt:135)
        at net.gotev.uploadservice.network.hurl.HurlStackRequest.getResponseBody(HurlStackRequest.kt:62)
        at net.gotev.uploadservice.network.hurl.HurlStackRequest.getResponse(HurlStackRequest.kt:115)
        at net.gotev.uploadservice.HttpUploadTask.upload(HttpUploadTask.kt:49)
        at net.gotev.uploadservice.UploadTask.run(UploadTask.kt:140)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by gotev** [comment]
Response body gets closed before the read is completed. 

Try also using OkHttp and let me know.

**Comment by EngKhAboshama** [comment]
@gotev Please what do you mean about trying also using OkHttp?

**Comment by gotev** [comment]
https://github.com/gotev/android-upload-service/wiki/Configuration#okhttpstack

**Comment by gotev** [comment]
Please also post Upload Service version used and please follow the issue template given next time, thanks 😉

**Comment by EngKhAboshama** [comment]
@gotev OK. I will check the doc of OkHttpStack and thank you in advance. 👍

**Comment by EngKhAboshama** [comment]
@gotev 
After I applied the OkHttpStack, I received the following crash

` java.lang.NoSuchMethodError: No virtual method log(ILjava/lang/String;Ljava/lang/Throwable;)V in class Lokhttp3/internal/platform/Platform; or its super classes (declaration of 'okhttp3.internal.platform.Platform' appears in /data/app/pharossolutions.app.schoolapp.teacher.debug-jWam9K8uv8HLKmknks91uA==/base.apk:classes3.dex)
        at okhttp3.logging.HttpLoggingInterceptor$Logger$Companion$DEFAULT$1.log(HttpLoggingInterceptor.kt:116)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:164)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2020-12-31 12:09:59.277 14828-14914/pharossolutions.app.schoolapp.teacher.debug E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: pharossolutions.app.schoolapp.teacher.debug, PID: 14828
    java.lang.NoSuchMethodError: No virtual method log(ILjava/lang/String;Ljava/lang/Throwable;)V in class Lokhttp3/internal/platform/Platform; or its super classes (declaration of 'okhttp3.internal.platform.Platform' appears in /data/app/pharossolutions.app.schoolapp.teacher.debug-jWam9K8uv8HLKmknks91uA==/base.apk:classes3.dex)
        at okhttp3.logging.HttpLoggingInterceptor$Logger$Companion$DEFAULT$1.log(HttpLoggingInterceptor.kt:116)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:164)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)`

I wrote the following code inside onCreate function inside the Application class: 

`        UploadServiceConfig.initialize(
            context = this,
            defaultNotificationChannel = NotificationHelperUtils.UPLOADING_CHANNEL_ID,
            debug = BuildConfig.DEBUG
        )
        UploadServiceConfig.retryPolicy = RetryPolicyConfig(
            initialWaitTimeSeconds = 1,
            maxWaitTimeSeconds = 1,
            multiplier = 1,
            defaultMaxRetries = 0
        )
        val client = getOkHttpClient(this)
        UploadServiceConfig.httpStack = OkHttpStack(client)
        UploadServiceConfig.placeholdersProcessor = CustomPlaceholdersProcessor(this)`

So what is wrong in the above code?

**Comment by EngKhAboshama** [comment]
Note that I use the dependances  
    implementation 'com.squareup.retrofit2:retrofit:2.6.2'
    implementation 'com.squareup.retrofit2:converter-jackson:2.3.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.2.1'

    ext.uploadServiceVersion = '4.4.1'
    implementation "net.gotev:uploadservice:$uploadServiceVersion"
    implementation "net.gotev:uploadservice-okhttp:$uploadServiceVersion"

**Comment by gotev** [comment]
NoSuchMethodExceptions usually happens with ProGuard on and missing rules or missing packages at runtime.

**Comment by gotev** [comment]
Just by copying and pasting the issue you reported on google search I found the following: https://github.com/square/okhttp/issues/2839 which is a more accurate answer.

**Comment by EngKhAboshama** [comment]
@gotev After upgrading the versions, the app works well now. 
Thank you :)

**Comment by gotev** [comment]
Awesome 😎
