### ISSUE TITLE
App crashing sometime randomly.

### ISSUE THREAD

**Issue by wahib922** [gotev/android-upload-service#560]
Fatal Exception: android.app.RemoteServiceException Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{f69fe5 u0 com.idrive.zipdrive/org.zipdrive.services.UploadFileService}

Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{f69fe5 u0 com.idrive.zipdrive/org.zipdrive.services.UploadFileService}
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1871)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7037)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by gotev** [comment]
Please fill in also the required information requested by the issue template.
