### ISSUE TITLE
Crash in 4.5.2

### ISSUE THREAD

**Issue by harshit-dwivedi** [gotev/android-upload-service#566]
**Describe the bug**
I am getting this error in v4.5.2 however same implementation is working in 4.4.0

2021-01-30 12:27:25.490 19112-19112/com.rotatingmind.brainy E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.rotatingmind.brainy, PID: 19112
    android.app.RemoteServiceException: Bad notification for startForeground
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2161)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:238)
        at android.app.ActivityThread.main(ActivityThread.java:7824)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
2021-01-30 12:27:25.500 19112-19617/com.rotatingmind.brainy E/UploadService: UploadTask - (uploadId: ba19a6c1-ac15-4dad-abd4-d7509ef80e67) - error
    net.gotev.uploadservice.exceptions.UserCancelledUploadException: User cancelled upload
        at net.gotev.uploadservice.UploadTask.onUserCancelledUpload(UploadTask.kt:254)
        at net.gotev.uploadservice.UploadTask.run(UploadTask.kt:171)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Expected behavior**
Working in 4.4.0.

**Comment by gotev** [comment]
File a test case which replicates this scenario 😉

**Comment by gotev** [comment]
@harshit-dwivedi how can this be replicated? Without steps to reproduce systematically or a test, nothing can be done to address an eventual library issue and I have to close this. Looking forward to hear from you 😉

**Comment by maxis7567** [comment]
I had the same problem after I implemented firebase notification service. gotev version 4.7.0
