### ISSUE TITLE
Stop Observing from RequestObserver using unregister causing a crash.

### ISSUE THREAD

**Issue by Sushant078** [gotev/android-upload-service#636]
**First of all thanks for such a great library!**

**Problem**
(using version 4.7.0)
Now there's a crash i'm facing, I'm using the RequestObservers inside my adapter and the lifecycle context is my activity along with context which is applicationContext. now i want to stop and delete RequestObservers inside my ViewHolder whenever it is recycled (becuase adapter has other items as well which are not meant to be observed ), Heres the code for better understanding:

```kotlin

      override fun onViewRecycled(holder: RecyclerView.ViewHolder) {
        super.onViewRecycled(holder)
        holder.requestObserver?.let {
            try{
                it.unregister()
            }catch (e:Exception){
                e.printStackTrace()
            }

        }
    }


    class FileItemVH(itemView: View) : RecyclerView.ViewHolder(itemView) {
        val binding = MyView.bind(itemView)
        var requestObserver: RequestObserver? = null
        fun bind(data: RepositoryFile, context: Context,adapterPosition:Int,requestObserverDelegate: RequestObserverDelegate) {
          
 
            try {
                requestObserver?.unregister()
            }catch (e:IllegalArgumentException){
                Log.e("Exce","Exce",e)
            }

            // This causes the crash, i.e when the RequestObserver is unregistered i get a crash when preview button is clicked
             binding.previewBtn.setSafeOnClickListener{
             val intent = Intent(context, Preview::class.java)
              intent.putExtra("url", data.asset?.url)
              context.startActivity(intent)
              }


            if (data.isUploading) {
                try {
                    requestObserver = RequestObserver(
                        context.applicationContext,
                        (context as Activity) as LifecycleOwner,
                        requestObserverDelegate
                    ) {
                            (uploadId): UploadInfo -> uploadId.startsWith("RepositoryUpload${data.uploadID}")
                    }
                }catch (e:IllegalArgumentException){
                    e.printStackTrace()
                }
            } else{
                try{
                      requestObserver?.unregister()
                      requestObserver = null
                } catch (e:Exception) { e.printStackTrace() }
                binding.progress.visibility = View.GONE
                binding.ivDelete.setOnClickListener(null)
            }
        }
    }
```

Whenever the views are recycled meaning the requestObserver is unregistered and i try to open an item using ```previewBtn```  which opens a new activity then the app immediately crashes with the following message

```
 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: MyProcess, PID: 10156
    java.lang.RuntimeException: Unable to pause activity {MyActivity}: java.lang.IllegalArgumentException: Receiver not registered: net.gotev.uploadservice.observer.request.RequestObserver@956bb73
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5071)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5022)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4974)
        at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:48)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:179)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7879)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: java.lang.IllegalArgumentException: Receiver not registered: net.gotev.uploadservice.observer.request.RequestObserver@956bb73
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1662)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1842)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:812)
        at net.gotev.uploadservice.observer.request.BaseRequestObserver.unregister(BaseRequestObserver.kt:40)
        at net.gotev.uploadservice.observer.request.RequestObserver.unregister(RequestObserver.kt:44)
        at net.gotev.uploadservice.observer.request.RequestObserver_LifecycleAdapter.callMethods(RequestObserver_LifecycleAdapter.java:31)
        at androidx.lifecycle.SingleGeneratedAdapterObserver.onStateChanged(SingleGeneratedAdapterObserver.java:31)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
        at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:290)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:308)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:151)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
        at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPrePaused(ReportFragment.java:201)
        at android.app.Activity.dispatchActivityPrePaused(Activity.java:1462)
        at android.app.Activity.performPause(Activity.java:8519)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1621)
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5061)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5022) 
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4974) 
        at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:48) 
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:179) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7879) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```
is there any method to stop and unregister the requestObserver? or is there any other method that i can use to handle thiss problem?

**Comment by gotev** [comment]
The problem is because you're using the RequestObserver inside a ViewHolder. You should instead use it in the containing Fragment or Activity.
