### ISSUE TITLE
Please add support for Android 34

### ISSUE THREAD

**Issue by tobias-r** [gotev/android-upload-service#642]
Caused by: java.lang.SecurityException: ************: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3041)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3024)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2966)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
                                                                                                    	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
                                                                                                    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
                                                                                                    	at net.gotev.uploadservice.observer.request.BaseRequestObserver.register(BaseRequestObserver.kt:36)
                                                                                                    	at net.gotev.uploadservice.observer.request.GlobalRequestObserver.<init>(GlobalRequestObserver.kt:12)
                                                                                                    	at net.gotev.uploadservice.observer.request.GlobalRequestObserver.<init>(GlobalRequestObserver.kt:6)
                                                                                                    	at net.gotev.uploadservice.observer.request.GlobalRequestObserver.<init>(Unknown Source:16)

**Comment by kabirnayeem99** [comment]
Yes. This issue is legit. Please, fix it to complete adding support to Android 34.

**Comment by kabirnayeem99** [comment]
Please check this [PR](https://github.com/gotev/android-upload-service/pull/644) which resolves this issue.

**Comment by tolew1** [comment]
@gotev is there any update for adding that PR or have another fix? This makes Android 14 crash.

**Comment by gotev** [comment]
Enjoy 🎉 https://github.com/gotev/android-upload-service/releases/tag/4.9.0
