### ISSUE TITLE
Missing default constructor for SchemeHandler classes

### ISSUE THREAD

**Issue by rtsm** [gotev/android-upload-service#651]
Fails on runtime when app build on CI with jdk17 

` java.lang.InstantiationException: java.lang.Class<net.gotev.uploadservice.schemehandlers.FileSchemeHandler> cannot be instantiated
                                                                                                    	at java.lang.Class.newInstance(Native Method)
                                                                                                    	at net.gotev.uploadservice.UploadServiceConfig.getSchemeHandler(UploadServiceConfig.kt:284)
                                                                                                    	at net.gotev.uploadservice.data.UploadFile$handler$2.invoke(UploadFile.kt:39)
                                                                                                    	at net.gotev.uploadservice.data.UploadFile$handler$2.invoke(UploadFile.kt:38)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at net.gotev.uploadservice.data.UploadFile.getHandler(UploadFile.kt:38)
                                                                                                    	at net.gotev.uploadservice.protocols.multipart.MultipartUploadRequest.addFileToUpload(MultipartUploadRequest.kt:56)`

**Comment by gotev** [comment]
Thank you for the heads up! Could you please share how you resolved the issue so I could add it to the wiki?

**Comment by gotev** [comment]
found a way to do that (https://github.com/gotev/android-upload-service/commit/56dfdcc71852007bf23d46cd40de538ca3c2665e) and released `4.9.1`
