### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by nannan111** [gotev/android-upload-service#662]
UploadTask - (uploadId: 1) - error on attempt 1. Waiting 1s before next attempt.
                                                                                                    java.lang.OutOfMemoryError: Failed to allocate a 314860912 byte allocation with 25165824 free bytes and 60MB until OOM, target footprint 364148440, growth limit 402653184
                                                                                                    	at okio.Buffer.readByteArray(Buffer.kt:1085)
                                                                                                    	at okio.Buffer.readByteArray(Buffer.kt:1080)
                                                                                                    	at okio.RealBufferedSource.readByteArray(RealBufferedSource.kt:241)
                                                                                                    	at okhttp3.ResponseBody.bytes(ResponseBody.kt:124)
                                                                                                    	at net.gotev.uploadservice.okhttp.OkHttpExtensionsKt.bodyBytes(OkHttpExtensions.kt:21)
                                                                                                    	at net.gotev.uploadservice.okhttp.OkHttpExtensionsKt.asServerResponse(OkHttpExtensions.kt:23)
                                                                                                    	at net.gotev.uploadservice.okhttp.OkHttpStackRequest.getResponse(OkHttpStackRequest.kt:95)
                                                                                                    	at net.gotev.uploadservice.HttpUploadTask.upload(HttpUploadTask.kt:50)
                                                                                                    	at net.gotev.uploadservice.UploadTask.run(UploadTask.kt:144)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:930)

**Comment by gotev** [comment]
Your server is returning over 314MB of payload size as the upload response. That's causing the issue here, because the system is trying to allocate all that in RAM. The server should return a small payload, possibly a JSON.
